# Update the esphome/secrets.yaml file to contain:

api_encryption_key: your_value_here
wifi_ssid: your_value_here
wifi_password: your_value_here
wifi_ap_password: your_value_here

# Or place all secrets in the home assistant secrets.yaml file and update the esphome/secrets.yaml file to include the home assistant secrets by adding the following line (but uncommented)
# <<: !include ../secrets.yaml